############################################################
#
# web访问端口号 约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource: # 数据源的相关配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xxxx.xxx.xxx.xxx:3306/foodie-shop?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: xxxx
      password: xxxxxxxx
      # 配置初始化大小/最小/最大[仅用于测试，生成环境需要修改哦]
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 一个连接在池中最小生存的时间
      time-between-eviction-runs-millis: 300000
      # 指定获取连接时连接校验的sql查询语句
      # validation-query: SELECT 'x'
      # 验证连接的有效性
      test-while-idle: true
      # 获取链接时验证，会影响性能(不建议 true)
      test-on-borrow: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20


  jackson:
    serialization:
      fail_on_empty_beans: false
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    # redis服务器地址
    host: xxx.xx.xxxx.xxx
    # redis端口
    port: 9999
    # redis连接超时时间
    timeout: 4000
    # redis 数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 4
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    password: xxxxxxxxxx
#
# mybatis 配置
#
############################################################
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml # mybatis 配置文件
  tyape-aliases-packge: com.isyxf.sso.cas.pojo # 所有POJO类所在包路径
  mapper-locations: classpath*:mybatis/mapper/*.xml # mapper映射文件


